services:
  pythonapp:
    build: ./systemPHR/
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - mysql
    volumes:
      - ./systemPHR:/usr/app/src
    ports:
      - '8010:8010'

  mysql:
    build: ./mysql/database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
